
<div id="loginbox">
   
     <div class="clr"></div>
    <form method="post" id="loginForm" action="<?php echo $this->url(array('module' => 'login', 'controller' => 'login', 'action' => 'index'), 'default', true); ?>" enctype="multipart/form-data">
        <!--  start login-inner -->
        <div id="login-inner">
            <div class="clr"></div>
	     <span class="errorLogin" id="error" style=" display:none;"><b>Incorrect Login!</b></span>
	     <div class="clr"></div>
            <?php echo $this->partial('error.phtml', array('form' => $this->form)); ?>
            <table border="0" cellpadding="0" cellspacing="0">
                <tr>
                    <th>Username</th>
                    <td><?php echo $this->partial('element.phtml', array('element' => $this->form->username)); ?></td>
                </tr>
                <tr>
                    <th>Password</th>
                    <td><?php echo $this->partial('element.phtml', array('element' => $this->form->password)); ?></td>
                </tr>
                <tr>
                    <th></th>
                    <td valign="top"><input type="checkbox" value="1" name="remember" class="checkbox-size" id="login-check" /><label for="login-check">Remember me</label></td>
                </tr>
                <tr>
                    <th></th>
                    <td><input type="button" id="login" class="submit-login" value="Login" /></td>
                </tr>
            </table>
        </div>
    </form>
    <!--  end login-inner -->
    <div class="clr"></div>
    <!--    <a href="" class="forgot-pwd">Forgot Password?</a>-->
</div>
<script>
    $(document).on('click','#login', function(){
        $("#loginForm").ajaxForm({
            dataType:'json',
            success:function(data){
                
                if(data != ''){
                    if(data['success'] != undefined){
                        if(data['success'] == 'Parent'){
                            window.location.href= '<?php echo $this->url(array(), 'dashboard', true); ?>';
                        }else{
                            window.location.href= '<?php echo $this->url(array('module' => 'admin', 'controller' => 'acl', 'action' => 'dashboard'), 'default', true); ?>';   
                        }
                    }else{
                        $.each(data,function(key,val){
                            $('#error').show();
    
                        })
                    }
                }
            }
        }).submit();
    });
    $(document).keydown(function(e){
        if(e.keyCode == 13){
            if ( $("*:focus").is("input") ){
                 $('#login').click();
            }
        }
    })
</script>