<style>
    body {
    background-color: #b0c4de;
}
</style>
<div class="login_container">
    <?php if(count($this->form->getMessages())) {
        $messages = $this->form->getMessages();?>
    <div class="alert alert-danger">
        <ul>
            <?php foreach($messages as $row){?>
            <li class="error"> <?php echo( (is_array($row))?(current ($row)) : $row ); ?> </li>
            <?php } ?>
        </ul>
    </div>
    <?php } ?>
    <form method="post" action="<?php echo $this->url(array('module' => 'login', 'controller' => 'login', 'action' => 'index'), 'default', true); ?>">
        <div class="login_msg mL10">
            <div id="dd" class="wrapper-dropdown-4">
                <?php echo $this->form->username; ?>
            </div>
            ​</div>
        <div class="login_msg mL10">
            <div id="dd" class="wrapper-dropdown-4 mt0" >
                <?php echo $this->form->password; ?>
            </div>
            ​</div>
        <input id="login" name="" type="submit" class="login_btn" value="Log-in" />
        <span class="pt11">
            <input type="checkbox" name="remember" value="1" id="remember" class="css-checkbox"
                   /><label for="remember" class="css-label m00 txt_14 w95">Remember Me</label>
        </span>
    </form>
</div>

<script>
    $(document).keydown(function(e) {
        if (e.keyCode == 13) {
            if ($("*:focus").is("input")) {
                $('#login').click();
            }
        }
    })
</script>