<div class="wrap">
    <div class="wrap-top">
        <div class="wrap-content" style="min-height: 600px; overflow: auto; width: 978px; margin-left: 7px;">
            <div style="margin: 40px 20px;">
                <h1>An error occurred</h1>
                <h2><?php echo $this->message ?></h2>
                <?php if (isset($this->exception)): ?>

                    <h3>Exception information:</h3>
                    <p>
                        <b>Message:</b> <?php echo $this->exception->getMessage() ?>
                    </p>

                    <h3>Stack trace:</h3>
                    <pre><?php echo $this->exception->getTraceAsString() ?>
                    </pre>

                    <h3>Request Parameters:</h3>
                    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
                    </pre>

                <?php endif ?>
            </div>
        </div>
    </div>
</div>