<header>
    <section>
        <div class="bg">
            <div class="wrapper">
                <div class="logo"></div>
                <?php $session = new Zend_Session_Namespace('userObj');
                    $userObj = $session->__get('userObj');
                    $usertype = $userObj['user_type'];
                    ?>
                <ul>
                    <li><a href="<?php echo $this->url(array(), 'patient_orders', true); ?>">Results</a></li>
                    <?php if($usertype == 'operator'){ ?>
                    <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'orders'), 'orders', true); ?>">Orders</a></li>
                    <?php } ?>
                    <li class="mR0"><a href="<?php echo $this->url(array('module' => 'login', 'controller' => 'login', 'action' => 'logout'), 'default', true); ?>">Logout</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section class="notfy-panel">
        <div class="notfy-inner">
            <div class="user_info">
                <p class="welcome-txt"> <span>Welcome</span> <span class="name"><a href="javascript:void(0)"><?php echo $userObj['first_name']. ' '. $userObj['last_name']?></a><i></i></span> </p>
            </div>
            <div class="clr"></div>
        </div>
    </section>
</header>