<header>
    <section>
        <div class="bg">
            <div class="wrapper">
                <div class="logo"></div>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Order Management</a></li>
                    <li class="mR0"><a href="#">Result Management</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section class="notfy-panel">
        <div class="notfy-inner">
            <div class="user_info">
                <p class="thumb"><img src="images/user_img.png" width="103" height="103" /></p>
                <p class="welcome-txt"> <span>Welcome</span> <span class="name"><a href="#">Amy Admin</a><i></i></span> </p>
            </div>
            <div class="msg_panel">
                <a href="#" class="notify"><i class="icons"></i> Notifications ( <span>5</span> )</a>
            </div>
            <div class="clr"></div>
        </div>
    </section>
</header>