<header>
    <section>
        <div class="bg">
            <div class="wrapper">
                <div class="logo"></div>
                <?php $session = new Zend_Session_Namespace('userObj');
                    $userObj = $session->__get('userObj');
                    $usertype = $userObj['user_type'];
                    ?>
                <ul>
                    <li><a href="#">Home</a></li>
                    <?php if($usertype == 'operator'){ ?>
                    <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'orders'), 'orders', true); ?>">Orders</a></li>
                    <?php } ?>
                    <li class="mR0"><a href="<?php echo $this->url(array('module' => 'login', 'controller' => 'login', 'action' => 'logout'), 'default', true); ?>">Logout</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section class="notfy-panel">
        <div class="notfy-inner">
            <div class="user_info">
                <p class="thumb"><img src="images/user_img.png" width="103" height="103" /></p>
                <p class="welcome-txt"> <span>Welcome</span> <span class="name"><a href="#">Amy Admin</a><i></i></span> </p>
            </div>
            <div class="msg_panel">
                <a href="#" class="notify"><i class="icons"></i> Notifications ( <span>5</span> )</a>
            </div>
            <div class="clr"></div>
        </div>
    </section>
</header>