<section class="msgs_box">
    <div class="msgs_links">
        <?php if($this->user_type=='operator'){ ?>
        <h1>Admin Panel</h1>
        <?php } else{ ?>
        <h1>Patient Portal</h1>
        <?php }  ?>
        
        <div class="clr"></div>
    </div>
    <section class="drop_downs no-bdr">
        <div class="tab_panel">
            <h3><?php echo $this->user_type=='operator'? 'Enter':'View'; ?> Results</h3>
            <div class="clr"></div>
            <div class="data_listing">
                <div class="data_listing_header">
                    <p class="heading_1 w230">Name</p>
                    <p class="heading_1 w190 pL20">Order</p>
                    <p class="heading_1 w190">Total Test</p>
                    <p class="heading_1 w190">Calculated Tests</p>
                    <p class="heading_1 w190">Created At</p>
                    <div class="clr"></div>
                </div>
                <div class="clr"></div>
                <?php foreach($this->patients as $patient){ ?>
                    <ul>
                        <li class="w230 pL25"><?php echo $patient['name']; ?></li>
                        <li class="w190 pL15"><?php echo $patient['order_id']; ?></li>
                        <li class="w190 pL22"><?php echo $patient['total_tests']; ?></li>
                        <li class="w190 pL15"><?php echo !empty($patient['total_results_calculated'])?$patient['total_results_calculated']:0; ?></li>
                        <li class="w190 pL16"><?php echo date('m-d-Y', strtotime($patient['created_at'])); ?></li>
                        <li class="last w80">
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'vieworder', 'id'=>$patient['order_id']), 'vieworder', true); ?>"><i class="icons eye"></i></a>
                        </li>
                    </ul>
                <?php } ?>
                <div class="clr"></div>
            </div>
            <div class="clr"></div>
        </div>

        <div class="clr"></div>
    </section>
    <div class="clr"></div>
</section>
<input type='text' id='mail_sent' value='<?php echo $this->mail_sent; ?>'>
<script>
    $(document).ready(function(){
        if($('#mail_sent').val() == 'mail_sent'){
            showMsg('Email sent successfully to your email address');
        }
    });
</script>
