<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script src="/assets/js/fcbkcomplete.js" type="text/javascript" charset="utf-8"></script>   
 
<style>
    .ui-datepicker{
	font-family: "Trebuchet MS", "Helvetica", "Arial",  "Verdana", "sans-serif";
	font-size: 62.5%;
}
.facebook-auto {
    margin-top: 0px;
}
</style>
<section class="msgs_box">
    <div class="msgs_links">
        <h1>Enter Test Order</h1>
        <div class="clr"></div>
    </div>
    <form class="frm-patient">
        <input name="id" type="hidden" class="id"></input>
        <input name="order_id" type="hidden" class="order_id"></input>
        <a class="compse_btn mr40 new" style="margin-right: 90px!important" href="javascript:void(0)">New</a>
        <a class="compse_btn submit" href="javascript:void(0)">Submit</a>
        <section class="drop_downs no-bdr">
        <div class="tab_gen_info pb38">
            <h3><i class="up_mark icons"></i><i class="side_mark"></i>Patient Information</h3>

            <article class="left w560">
                <p><label class="mt0">Search Patient</label><span><input id="search" name="" type="text" class="create_inpt" tabIndex="1" style="width:433px" /></span></p>
                <p><label class="mt12">First Name</label><span><?php echo $this->form->first_name ?></span></p>
                <p><label class="mt12">Phone</label><span><?php echo $this->form->phone_number ?></span></p>
                <p><label class="mt12">Birthday</label><span><?php echo $this->form->birthday ?></span></p>
                <p><label class="mt12">Email</label><span><?php echo $this->form->email ?></span></p>
            </article>
            <article class="left w560 mL52">
                <!--<p style="margin-top: 22px"><label>&nbsp;</label><span class="pL25">&nbsp; </span></p>-->
                <p style="margin-top: 12px"><label>Patient ID</label><span class="pL25 id"></span></p>
                <p class="mt20"><label >Last Name</label><span><?php echo $this->form->last_name ?></span></p>
                <p><label class="mt12">Address</label><span><?php echo $this->form->address ?></span></p>
                <p><label class="mt12">Sex</label>
                    <!--<div class="wrapper-demo mL0 mt10">-->
                    <?php echo $this->form->sex ?>
                    <!--​</div>-->
                </p>
                <p><label class="mt12">M.R.N.No.</label><span><?php echo $this->form->m_r_no ?></span></p>
            </article>
            <div class="clr"></div>  
        </div>

<div class="tab_gen_info pb38">
             	<h3><i class="up_mark icons"></i><i class="side_mark"></i>Test Information</h3>
                   <article class="left w560">
                    <p style="margin-top: 12px"><label>Order ID</label><span class="pL25 order-id"></span></p>
                    <p class="tests">
                        <?php foreach($this->tests as $test){ ?>
                                <ul class="test clr"> 
                                    <li style="list-style:none; float:left" class="mL52"> <input type="checkbox" name="test_id[]" value="<?php echo $test['id'] ?>"/> </li>
                                    <li style="list-style:none; float:left" class="mL20"><?php echo $test['name'] ?></li>
                                </ul>
                         <?php } ?>
                    </p>
               </article>
                
               <div class="clr"></div>  
             </div>

        <div class="clr"></div>
    </section>
    </form>
    <div class="clr"></div>
    <a href="javascript:void(0)" class="create_new_btn mL52 submit">Submit</a>
</section>
    <script>
    var patient_submit_url = "<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'postorder'), 'default', true); ?>";
    var fcbk_search_url = "<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'search'), 'default', true); ?>";
    var pat_search_rul = "<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'getpatient'), 'default', true); ?>";
    </script>
    <script src="/assets/js/orders.js" type="text/javascript" charset="utf-8"></script>   

