<style>
    ::-webkit-input-placeholder { font-size: 14px; }
::-moz-placeholder { font-size: 14px;} /* firefox 19+ */
:-ms-input-placeholder { font-size: 14px; } /* ie */
    input:-moz-placeholder { font-size: 14px; }
</style>
<section class="msgs_box">
    <div class="msgs_links">
        <h1>Enter Test Order Results</h1>
        <div class="clr"></div>
    </div>
    <section class="drop_downs no-bdr">
        <div class="tab_panel">
            <h3>Test Order</h3>
            <p><label class=" bold">Patient Name:</label><label class="mL10"><?php echo $this->patient[0]['name']; ?></label>
            <label class="mL25 bold">M.R.N.No:</label><label class="mL10"><?php echo $this->patient[0]['m_r_no']; ?></label>
            <label class="mL25 bold">Order No.:</label><label class="mL10"><?php echo $this->patient[0]['order_id']; ?></label>
            <label class="mL25 bold">Order Date:</label><label class="mL10"><?php echo date('m-d-Y', strtotime($this->patient[0]['date_in'])); ?></label>
            </p>
        
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'index'), 'patient_orders', true); ?>" class="compse_btn">Back</a>
            <a href="javascript:void(0)" class="compse_btn save-btn">Save Results</a>

            <div class="clr"></div>
            <form class="frm">
                <input type="hidden" name="order_id" value="<?php echo $this->patient[0]['order_id'];?> "></input>
            <div class="data_listing">
                <div class="data_listing_header">
                    <p class="heading_1 w300">Test Name</p>
                    <p class="heading_1 w300">Result</p>
                    <p class="heading_1 w300">Reference Value</p>
                    
                    <div class="clr"></div>
                </div>
                <div class="clr"></div>
                <?php foreach($this->patient as $test){ ?>
                    <ul>
                         <input type="hidden" name="test_id[]" value="<?php echo $test['test_id'];?> "></input>
                        <li class="w300 pL22"><?php echo $test['test_name']; ?></li>
                        <li class="w300 pL15"><?php echo '<input name="result[]" placeholder="Enter Result Here" class="result-input placeholder14" value="'.$test['results'].'" style="background:transparent;border: none;" type="text" />' ?></li>
                        <li class="w300 pL16"><?php echo $test['reference_value']; ?></li>
                        <li class="last w230">
                        </li>
                    </ul>
                <?php } ?>
                <div class="clr"></div>
            </div>
                </form>
            <div class="clr"></div>
        </div>

        <div class="clr"></div>
    </section>
    <div class="clr"></div>
</section>
<script>
    var save_result_url = "<?php echo $this->url(array('module' => 'admin', 'controller' => 'admin', 'action' => 'saveresult'), 'default', true); ?>"
</script>
 <script src="/assets/js/save_result.js" type="text/javascript" charset="utf-8"></script>   