<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" class="js opacity generatedcontent pointerevents">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Pathology</title>
        <link href="<?php echo $this->baseUrl('assets/css/styles.css'); ?>" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?php echo $this->baseUrl('assets/js/jquery-1.11.3.min.js'); ?>"></script>
    </head>
    <body>
                <?php echo $this->layout()->content; ?>
       </body>
</html>