<style>
    @page *{
    margin-top: 2.54cm;
    margin-bottom: 2.54cm;
    margin-left: 3.175cm;
    margin-right: 3.175cm;
}</style>
<style>
   table tr td{font-size: 20px;} 
</style>
<section class="msgs_box">
    <div class="msgs_links">
        <h1>My Report</h1>
        <div class="clr"></div>
    </div>
    <section class="drop_downs no-bdr">
        <div class="tab_panel">
            <table width="100%" style="border-top:1px solid;border-bottom:1px solid;">
                <tbody>
                    <tr style="height: 50px;">
                        <td width="200px;">Patient Name:</td>
                        <td width="200px;" style='font-weight:bold;'><?php echo $this->patients[0]['name']; ?></td>

                        <td width="200px;">Age:</td>
                        <td width="200px;" style='font-weight:bold;'><?php echo !empty($this->age)?$this->age.' Year': ''; ?></td>

                        <td width="200px;">Sex:</td>
                        <td width="200px;" style='font-weight:bold;'><?php echo $this->patients[0]['sex']; ?></td>
                    </tr>
                    <tr style="height: 50px;">
                        <td width="200px;">Ref. by Doctor:</td>
                        <td width="200px;" style='font-weight:bold;'>-</td>

                        <td width="200px;">M.R.No:</td>
                        <td width="200px;" style='font-weight:bold;'><?php echo $this->patients[0]['m_r_no']; ?></td>

                        <td width="200px;">Date In</td>
                        <td width="200px;" style='font-weight:bold;'><?php echo date('Y-m-d', strtotime($this->patients[0]['date_in'])); ?></td>
                    </tr>
                    <tr style="height: 50px;">
                        <td width="200px;">Specimen Type</td>
                        <td width="200px;" style='font-weight:bold;'>-</td>

                        <td width="200px;">Specimen:</td>
                        <td width="200px;" style='font-weight:bold;'>Brought to Lab</td>

                        <td width="200px;">Date Out</td>
                        <td width="200px;" style='font-weight:bold;'>-</td>
                    </tr>
                </tbody>
            </table>
            <table width='100%' style='margin-top:20px;'>
                <tbody>
                    <tr style='outline:1px solid;'><td style='text-align: center;'><h3><?php echo $this->patients[0]['test_name']; ?></h3></td></tr>
                    <tr><td>&nbsp;</td></tr>
                    <tr><td style='font-weight: bold;'>Complete Blood Count</td></tr>
                    <tr><td>&nbsp;</td></tr>
                    <tr>
                        <td>
                        <table style='margin-left:120px;'>
                            <thead>
                                <tr>
                                    <th width='300px' style="text-align: left;">Tests</th>
                                    <th width='300px' style="text-align: left;">Results</th>
                                    <th width='300px' style="text-align: left;">Units</th>
                                    <th width='300px' style="text-align: left;">Reference Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($this->patients as $patient){ ?>
                                <tr style='height:60px;'>
                                    <td width='300px' style="text-align: left;"><?php echo $patient['test_name']; ?></td>
                                    <td width='300px' style="text-align: left;"><?php echo $patient['results']; ?></td>
                                    <td width='300px' style="text-align: left;">g/dl</td>
                                    <td width='300px' style="text-align: left;"><?php echo $patient['reference_value']; ?></td>
                                </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    <td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="clr"></div>
    </section>
    <div class="clr"></div>
</section>