<section class="msgs_box">
    <div class="msgs_links">
        <h1>Report Management</h1>
        <div class="clr"></div>
    </div>
    <section class="drop_downs no-bdr">
        <div class="tab_panel">
            <h3 class='mb30'>Report View</h3>

            <table width="100%" style="border-top:1px solid;border-bottom:1px solid;">
                <tbody>
                    <tr style="height: 50px;">
                        <td width="200px;">Patient Name:</td>
                        <td width="300px;">Zainab</td>

                        <td>Age:</td>
                        <td>6 Year</td>

                        <td>Sex:</td>
                        <td>Female</td>
                    </tr>
                    <tr style="height: 50px;">
                        <td width="200px;">Ref. by Doctor:</td>
                        <td width="300px;">Dr, Abdul Samad Shakoori</td>

                        <td>M.R.No:</td>
                        <td>2149 (2710)</td>

                        <td>Date In</td>
                        <td>2015-06-28</td>
                    </tr>
                    <tr style="height: 50px;">
                        <td width="200px;">Specimen Type</td>
                        <td width="300px;">-</td>

                        <td>Specimen:</td>
                        <td>Brought to Lab</td>

                        <td>Date Out</td>
                        <td>2015-06-28</td>
                    </tr>
                </tbody>
            </table>
            <table width='100%' style='margin-top:20px;'>
                <tbody>
                    <tr style='outline:1px solid;'><td style='text-align: center;'>HAEMATOLOGY</td></tr>
                    <tr><td>&nbsp;</td></tr>
                    <tr><td>Complete Blood Count</td></tr>
                    <tr><td>&nbsp;</td></tr>
                    <tr>
                        <td>
                        <table style='margin-left:120px;'>
                            <thead>
                                <tr>
                                    <th width='300px' style="text-align: left;">Tests</th>
                                    <th width='300px' style="text-align: left;">Results</th>
                                    <th width='300px' style="text-align: left;">Units</th>
                                    <th width='300px' style="text-align: left;">Reference Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr style='height:60px;'>
                                    <td width='300px' style="text-align: left;">Haemoglobin</td>
                                    <td width='300px' style="text-align: left;">11.5</td>
                                    <td width='300px' style="text-align: left;">g/dl</td>
                                    <td width='300px' style="text-align: left;">M: 14-18 F:12-5</td>
                                </tr>
                                <tr style='height:60px;'>
                                    <td width='300px' style="text-align: left;">Haemoglobin</td>
                                    <td width='300px' style="text-align: left;">11.5</td>
                                    <td width='300px' style="text-align: left;">g/dl</td>
                                    <td width='300px' style="text-align: left;">M: 14-18 F:12-5</td>
                                </tr>
                                <tr style='height:60px;'>
                                    <td width='300px' style="text-align: left;">Haemoglobin</td>
                                    <td width='300px' style="text-align: left;">11.5</td>
                                    <td width='300px' style="text-align: left;">g/dl</td>
                                    <td width='300px' style="text-align: left;">M: 14-18 F:12-5</td>
                                </tr>
                                <tr style='height:60px;'>
                                    <td width='300px' style="text-align: left;">Haemoglobin</td>
                                    <td width='300px' style="text-align: left;">11.5</td>
                                    <td width='300px' style="text-align: left;">g/dl</td>
                                    <td width='300px' style="text-align: left;">M: 14-18 F:12-5</td>
                                </tr>
                            </tbody>
                        </table>
                    <td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="clr"></div>
    </section>
    <div class="clr"></div>
</section>